### ISSUE TITLE
Thank God u didnt leave

### ISSUE THREAD

**Issue by CoolCodingTeen231** [UnClausus-Ludi/Unblocked-game-Links#3]
So are u gonna stay on GitHub or leave idk

**Comment by UnClausus-Ludi** [comment]
IM BACK

**Comment by UnClausus-Ludi** [comment]
I had to lie sorry

**Comment by UnClausus-Ludi** [comment]
Here’s why I left

**Comment by UnClausus-Ludi** [comment]
https://github.com/UnClausus-Ludi/Deleted-Repo-Why

**Comment by UnClausus-Ludi** [comment]
Cause I’m not supposed to find games at school and list them

**Comment by UnClausus-Ludi** [comment]
Unblocked Games Is mostly used for school

**Comment by TrickJoker312** [comment]
wait what
DMCA by who?

**Comment by UnClausus-Ludi** [comment]
My school district

**Comment by UnClausus-Ludi** [comment]
They said they would go take it down so I did I didn’t want legal trouble but now I realize they can’t take it down With a DMCA or Taking me to court

**Comment by CoolCodingTeen231** [comment]
@UnClausus-Ludi buddy why tf did u say the d word in Roblox

**Comment by CoolCodingTeen231** [comment]
<img width="379" alt="Screenshot 2023-09-26 155401" src="https://github.com/UnClausus-Ludi/Unblocked-game-Links/assets/142688039/31984642-0ddf-4e10-8cab-94281f577921">

**Comment by UnClausus-Ludi** [comment]
Cause that’s what I like

**Comment by CoolCodingTeen231** [comment]
@UnClausus-Ludi 🤮💀Bro are u gay🤮💀

**Comment by UnClausus-Ludi** [comment]
![Parent 5](https://github.com/UnClausus-Ludi/Unblocked-game-Links/assets/131894406/e01d0e2f-da62-4828-b73c-60573e740888)

**Comment by UnClausus-Ludi** [comment]
Im bisexual

**Comment by UnClausus-Ludi** [comment]
I’m bisexual

**Comment by CoolCodingTeen231** [comment]
@UnClausus-Ludi then why didnt u say your in love with YouTube

**Comment by CoolCodingTeen231** [comment]
because there are both men and woman there

**Comment by CoolCodingTeen231** [comment]
@UnClausus-Ludi or say you are dating a Robot (because bisexual means you are in love with anyone with any gender)

**Comment by UnClausus-Ludi** [comment]
[HeymanClickthisLinks](Google.com) Bro

**Comment by DeusOmmuim** [comment]
[HeymanClickthisLinks](Google.com)
