### ISSUE TITLE
Yo.

### ISSUE THREAD

**Issue by TrickJoker312** [UnClausus-Ludi/Unblocked-game-Links#8]
You got any new proxies? Trying to download a game, but can't get passed the Securely.
I would appreciate it if you could link some proxies! Thank you so much! :D

**Comment by TrickJoker312** [comment]
PS. I don't think they can be Github links. They're blocked in my district.

**Comment by TrickJoker312** [comment]
Also, do you happen to have any PS1 emulators? Need it to play said game.

**Comment by UnClausus-Ludi** [comment]
Alr

**Comment by TrickJoker312** [comment]
...

**Comment by UnClausus-Ludi** [comment]
Google translate the links
